[workspace]
authors = ["Niteya Shah <niteya@vt.edu>", "Beau Johnston <johnstonbe@ornl.gov>"]
channels = ["conda-forge"]
name = "quantom"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = "3.10.*"
pip = "*"
setuptools = ">=80,<81"
ninja = ">=1.13,<2"
pytest = ">=8,<9"
matplotlib = ">=3.8,<4"
